### ISSUE TITLE
Failed to get the Songs

### ISSUE THREAD

**Issue by sandeepameba** [jkiddo/gmusic.api#17]
I have used this library in my code and when I try to use the search api like

QueryResults results = GoogleMusicApi.search(MainActivity.this, "rock");

It gave me this error message

Authentication error: Unable to respond to any of these challenges: {googlelogin=WWW-Authenticate: GoogleLogin realm="https://www.google.com/accounts/ClientLogin", service="sj"}

**Comment by jkiddo** [comment]
API is currently outdated and needs to get up to speed using https://github.com/simon-weber/gmusicapi - meaning there is a huge porting job to do
